/**
 * GET /api/alerts — Merged Alert Feed (System + Official NDMA SACHET)
 *
 * Returns two types of alerts clearly tagged:
 *   - "system"   : alerts generated by LandslideShield AI when a monitored
 *                  zone's ONNX-computed risk score crosses 76 (CRITICAL).
 *   - "official" : live alerts from the NDMA SACHET CAP feed, filtered to
 *                  states that overlap with monitored zones in the DB.
 *
 * NFR-05 compliance: every alert item carries `source` + `last_updated` timestamp.
 *
 * POST /api/alerts — Trigger alert evaluation (unchanged from previous behavior)
 */

import { NextRequest, NextResponse } from "next/server";
import { checkAndSendAlerts, getRecentAlerts } from "@/server/services/alertService";
import { fetchSachetAlerts } from "@/server/external-data/sachetClient";
import { query } from "@/server/db/client";

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Derives unique state names from the monitored zones in the DB,
 * so the SACHET feed can be filtered to relevant Indian states.
 * Returns an empty array if the DB is offline (→ all-India SACHET alerts returned).
 */
async function getMonitoredStates(): Promise<string[]> {
  try {
    const rows = await query<any[]>("SELECT name FROM zones");
    // Zone names typically include the state, e.g. "Wayanad, Kerala"
    // Extract the last comma-delimited segment as a rough state hint.
    const states = new Set<string>();
    for (const r of rows) {
      const parts = (r.name || "").split(",");
      if (parts.length > 1) {
        states.add(parts[parts.length - 1].trim());
      }
    }
    // Always include high-risk states in Himalayas and Western Ghats
    const alwaysInclude = [
      "Uttarakhand", "Himachal Pradesh", "Jammu & Kashmir",
      "Kerala", "Karnataka", "Tamil Nadu",
      "Sikkim", "Arunachal Pradesh", "Meghalaya", "Manipur",
      "Nagaland", "Mizoram", "Assam", "West Bengal",
      "Maharashtra", "Goa",
    ];
    alwaysInclude.forEach((s) => states.add(s));
    return Array.from(states);
  } catch {
    return []; // offline — return no filter (all national alerts)
  }
}

// ─── GET handler ──────────────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
  try {
    // 1. Fetch system-generated alerts from MySQL
    const systemAlerts = await getRecentAlerts(30);
    const systemNormalized = systemAlerts.map((a) => ({
      id: `sys-${a.id}`,
      source: "system" as const,
      zone_id: a.zone_id,
      zone_name: a.zone_name || a.zone_id,
      title: `Critical Risk — ${a.zone_name || a.zone_id}`,
      description: `System-generated alert. Zone risk score reached ${a.score_at_alert}/100 (${a.level}). Emergency email dispatch: ${a.email_sent ? "sent" : "pending"}.`,
      level: a.level,
      score_at_alert: a.score_at_alert,
      severity: a.level === "CRITICAL" ? "Extreme" : "Severe",
      email_sent: a.email_sent,
      last_updated: a.sent_at,
      sent_at: a.sent_at,
    }));

    // 2. Fetch official NDMA SACHET alerts (filtered to monitored states)
    const monitoredStates = await getMonitoredStates();
    const sachetResult = await fetchSachetAlerts(monitoredStates);
    const officialNormalized = sachetResult.alerts.map((a) => ({
      id: `sachet-${a.id}`,
      source: "official" as const,
      zone_id: null,
      zone_name: a.area || "National / Regional",
      title: a.title,
      description: a.description,
      level: a.severity.toUpperCase(),
      score_at_alert: null,
      severity: a.severity,
      event: a.event,
      area: a.area,
      state: a.state,
      onset: a.onset,
      expires: a.expires,
      feed_url: a.feed_url,
      email_sent: null,
      last_updated: a.last_updated,
      sent_at: a.onset,
    }));

    // 3. Combine — system alerts first (highest operational priority), then official
    const merged = [...systemNormalized, ...officialNormalized];

    return NextResponse.json({
      success: true,
      count: merged.length,
      system_count: systemNormalized.length,
      official_count: officialNormalized.length,
      sachet_feed_status: sachetResult.feed_status,
      sachet_fetched_at: sachetResult.fetched_at,
      sachet_message: sachetResult.message,
      alerts: merged,
    });
  } catch (error: any) {
    console.error("[GET /api/alerts] Error:", error.message);
    return NextResponse.json(
      { success: false, error: error.message || "Failed to retrieve alert records." },
      { status: 500 }
    );
  }
}

// ─── POST handler ─────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    const result = await checkAndSendAlerts();
    return NextResponse.json({
      success: true,
      message: "Evaluated zone risk scores and processed emergency alert triggers.",
      ...result,
    });
  } catch (error: any) {
    console.error("[POST /api/alerts] Error checking alerts:", error.message);
    return NextResponse.json(
      { success: false, error: error.message || "Failed to evaluate alert triggers." },
      { status: 500 }
    );
  }
}
